# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import flybrain_pb2 as flybrain__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in flybrain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlyBrainServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealth = channel.unary_unary(
                '/flybrain.FlyBrainService/GetHealth',
                request_serializer=flybrain__pb2.HealthRequest.SerializeToString,
                response_deserializer=flybrain__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/flybrain.FlyBrainService/GetVersion',
                request_serializer=flybrain__pb2.VersionRequest.SerializeToString,
                response_deserializer=flybrain__pb2.VersionResponse.FromString,
                _registered_method=True)
        self.GetTelemetry = channel.unary_unary(
                '/flybrain.FlyBrainService/GetTelemetry',
                request_serializer=flybrain__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=flybrain__pb2.TelemetryResponse.FromString,
                _registered_method=True)
        self.GetTelemetryStream = channel.unary_stream(
                '/flybrain.FlyBrainService/GetTelemetryStream',
                request_serializer=flybrain__pb2.TelemetryStreamRequest.SerializeToString,
                response_deserializer=flybrain__pb2.TelemetryResponse.FromString,
                _registered_method=True)
        self.Decide = channel.unary_unary(
                '/flybrain.FlyBrainService/Decide',
                request_serializer=flybrain__pb2.DecideRequest.SerializeToString,
                response_deserializer=flybrain__pb2.DecideResponse.FromString,
                _registered_method=True)
        self.IssueToken = channel.unary_unary(
                '/flybrain.FlyBrainService/IssueToken',
                request_serializer=flybrain__pb2.TokenRequest.SerializeToString,
                response_deserializer=flybrain__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.VerifyToken = channel.unary_unary(
                '/flybrain.FlyBrainService/VerifyToken',
                request_serializer=flybrain__pb2.VerifyRequest.SerializeToString,
                response_deserializer=flybrain__pb2.VerifyResponse.FromString,
                _registered_method=True)
        self.SendCommand = channel.unary_unary(
                '/flybrain.FlyBrainService/SendCommand',
                request_serializer=flybrain__pb2.CommandRequest.SerializeToString,
                response_deserializer=flybrain__pb2.CommandResponse.FromString,
                _registered_method=True)


class FlyBrainServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetHealth(self, request, context):
        """Health and version
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTelemetry(self, request, context):
        """Telemetry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTelemetryStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decide(self, request, context):
        """Decision making
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IssueToken(self, request, context):
        """Safety token management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCommand(self, request, context):
        """Commands
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlyBrainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=flybrain__pb2.HealthRequest.FromString,
                    response_serializer=flybrain__pb2.HealthResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=flybrain__pb2.VersionRequest.FromString,
                    response_serializer=flybrain__pb2.VersionResponse.SerializeToString,
            ),
            'GetTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTelemetry,
                    request_deserializer=flybrain__pb2.TelemetryRequest.FromString,
                    response_serializer=flybrain__pb2.TelemetryResponse.SerializeToString,
            ),
            'GetTelemetryStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTelemetryStream,
                    request_deserializer=flybrain__pb2.TelemetryStreamRequest.FromString,
                    response_serializer=flybrain__pb2.TelemetryResponse.SerializeToString,
            ),
            'Decide': grpc.unary_unary_rpc_method_handler(
                    servicer.Decide,
                    request_deserializer=flybrain__pb2.DecideRequest.FromString,
                    response_serializer=flybrain__pb2.DecideResponse.SerializeToString,
            ),
            'IssueToken': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueToken,
                    request_deserializer=flybrain__pb2.TokenRequest.FromString,
                    response_serializer=flybrain__pb2.TokenResponse.SerializeToString,
            ),
            'VerifyToken': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyToken,
                    request_deserializer=flybrain__pb2.VerifyRequest.FromString,
                    response_serializer=flybrain__pb2.VerifyResponse.SerializeToString,
            ),
            'SendCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommand,
                    request_deserializer=flybrain__pb2.CommandRequest.FromString,
                    response_serializer=flybrain__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flybrain.FlyBrainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flybrain.FlyBrainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlyBrainService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flybrain.FlyBrainService/GetHealth',
            flybrain__pb2.HealthRequest.SerializeToString,
            flybrain__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flybrain.FlyBrainService/GetVersion',
            flybrain__pb2.VersionRequest.SerializeToString,
            flybrain__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flybrain.FlyBrainService/GetTelemetry',
            flybrain__pb2.TelemetryRequest.SerializeToString,
            flybrain__pb2.TelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTelemetryStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/flybrain.FlyBrainService/GetTelemetryStream',
            flybrain__pb2.TelemetryStreamRequest.SerializeToString,
            flybrain__pb2.TelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Decide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flybrain.FlyBrainService/Decide',
            flybrain__pb2.DecideRequest.SerializeToString,
            flybrain__pb2.DecideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IssueToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flybrain.FlyBrainService/IssueToken',
            flybrain__pb2.TokenRequest.SerializeToString,
            flybrain__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flybrain.FlyBrainService/VerifyToken',
            flybrain__pb2.VerifyRequest.SerializeToString,
            flybrain__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flybrain.FlyBrainService/SendCommand',
            flybrain__pb2.CommandRequest.SerializeToString,
            flybrain__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
