#!/usr/bin/env python3
"""Generate summary markdown from resource CSV and test results."""
import csv
import sys
import json
from pathlib import Path
from typing import List, Dict, Any
from datetime import datetime


def read_csv(csv_path: Path) -> List[Dict[str, Any]]:
    rows = []
    with open(csv_path, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append({
                "timestamp": float(row["timestamp"]),
                "cpu_percent": float(row["cpu_percent"]) if row["cpu_percent"] != "NaN" else None,
                "mem_percent": float(row["mem_percent"]) if row["mem_percent"] != "NaN" else None,
                "temp_c": float(row["temp_c"]) if row["temp_c"] != "NaN" else None,
                "power_w": float(row["power_w"]) if row["power_w"] != "NaN" else None,
            })
    return rows


def compute_stats(rows: List[Dict[str, Any]]) -> Dict[str, Any]:
    if not rows:
        return {}

    cpu_vals = [r["cpu_percent"] for r in rows if r["cpu_percent"] is not None]
    mem_vals = [r["mem_percent"] for r in rows if r["mem_percent"] is not None]
    temp_vals = [r["temp_c"] for r in rows if r["temp_c"] is not None]
    power_vals = [r["power_w"] for r in rows if r["power_w"] is not None]

    def stats(vals):
        if not vals:
            return {"avg": None, "min": None, "max": None, "p50": None, "p95": None}
        vals_sorted = sorted(vals)
        n = len(vals_sorted)
        return {
            "avg": sum(vals) / n,
            "min": vals_sorted[0],
            "max": vals_sorted[-1],
            "p50": vals_sorted[n // 2],
            "p95": vals_sorted[int(n * 0.95)],
        }

    return {
        "cpu": stats(cpu_vals),
        "mem": stats(mem_vals),
        "temp": stats(temp_vals),
        "power": stats(power_vals),
        "samples": len(rows),
        "duration_s": rows[-1]["timestamp"] - rows[0]["timestamp"] if len(rows) > 1 else 0,
    }


def read_test_results(results_path: Path) -> Dict[str, Any]:
    """Try to read pytest JSON report if exists."""
    if results_path.exists():
        with open(results_path, "r") as f:
            return json.load(f)
    return {}


def main():
    if len(sys.argv) < 3:
        print("Usage: generate_summary.py <resources.csv> <output.md> [test_results.json]")
        sys.exit(1)

    csv_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    test_results_path = Path(sys.argv[3]) if len(sys.argv) > 3 else None

    rows = read_csv(csv_path)
    stats = compute_stats(rows)
    test_results = read_test_results(test_results_path) if test_results_path else {}

    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w") as f:
        f.write(f"# T002 Resource Monitoring Summary\n\n")
        f.write(f"**Generated**: {datetime.now().isoformat()}\n")
        f.write(f"**CSV Source**: {csv_path}\n")
        f.write(f"**Samples**: {stats.get('samples', 0)}\n")
        f.write(f"**Duration**: {stats.get('duration_s', 0):.1f}s\n\n")

        f.write("## Resource Statistics\n\n")
        f.write("| Metric | Avg | Min | Max | P50 | P95 |\n")
        f.write("|--------|-----|-----|-----|-----|-----|\n")

        for metric in ["cpu", "mem", "temp", "power"]:
            s = stats.get(metric, {})
            unit = {"cpu": "%", "mem": "%", "temp": "°C", "power": "W"}[metric]
            name = {"cpu": "CPU", "mem": "Memory", "temp": "Temperature", "power": "Power"}[metric]
            if s.get("avg") is not None:
                f.write(f"| {name} | {s['avg']:.1f}{unit} | {s['min']:.1f}{unit} | {s['max']:.1f}{unit} | {s['p50']:.1f}{unit} | {s['p95']:.1f}{unit} |\n")
            else:
                f.write(f"| {name} | N/A | N/A | N/A | N/A | N/A |\n")

        f.write("\n## Test Results\n\n")
        if test_results:
            f.write(f"```json\n{json.dumps(test_results, indent=2)}\n```\n")
        else:
            f.write("*No test results JSON found. Run with `pytest --json-report` to capture.*\n")

        f.write("\n## Observations\n\n")
        cpu_avg = stats.get("cpu", {}).get("avg")
        temp_max = stats.get("temp", {}).get("max")
        if cpu_avg is not None:
            f.write(f"- Average CPU usage: **{cpu_avg:.1f}%**\n")
        if temp_max is not None:
            f.write(f"- Peak temperature: **{temp_max:.1f}°C**\n")
            if temp_max > 80:
                f.write(f"  ⚠️ **Thermal throttling likely** (Steam Deck throttles ~80-85°C)\n")
        if stats.get("power", {}).get("avg") is None:
            f.write(f"- Power reading: **Unavailable** (RAPL/hwmon not accessible)\n")

        f.write("\n---\n*Generated by `scripts/generate_summary.py`*\n")


if __name__ == "__main__":
    main()